name: My Test WorkFlow - Repo2
'on':
  repository_dispatch:
    types: [trigger-workflow]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-1
        run: echo "STEP-1 Executed"
